[versions]
lombok = "1.18.34"
annotations = "24.1.0"
quala-bom = "1.0.13-RELEASE"

[libraries]
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

quala-bom = { group = "dev.golgolex", name = "quala-bom", version.ref = "quala-bom" }